# Generated by Django 4.1.3 on 2022-11-08 10:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='categories',
            field=models.TextField(default=api.models.default_categories_json),
        ),
    ]
