# Generated by Django 4.1.3 on 2022-11-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_balance_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='rest_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
